= Administrator guide
Doc Writer <esthesis@eurodyn.com>
:toc:
:imagesdir: assets/images
:homepage: https://esthesis.com
:icons: font
:sectanchors:
:sectlinks:
:sectnums:

This is the _Administrator guide_ for _esthesis_ platform. It shows you in detail all the different options and configuration knobs of _esthesis_ while providing you valuable hints & tips on how you can use _esthesis_ in production.

== Quick configuration
How many times have you installed a new product, finding yourself having to read a ton of documentation on how to set it up before you can even start testing it? Well, _esthesis_ might also have a ton of documentation, however that does not prevent us from showing you how you can quickly set it up to have a test working platform in under 10'. Ready?

TIP: Make sure you have a complete installation done first following your preferred method from the link:installation_guide.adoc[Installation guide].

WARNING: The quick setup instructions depicted here are not suggested for anything else than a test lab. If you consider using _esthesis_ in anything wider than your local lab-network make sure you follow (TBC) first.

=== Platform server configuration

* Login to _esthesis_ management ui.
* If you have not already created a Certificate Authority as part of your installation procedure, create one now.
* Similarly, make sure you have created a Certificate for the _esthesis_ platform signed by the above Certificate Authority.
* Create a tag to identify your devices with.
* Go to Settings > Security and choose the Platform certificate.
* Go to Settings > Device registration and choose the Certificate Authority.
* Go to Settings > Device registration and choose 'Open registration' (or any other mode you need).
* Go to Settings > Networking and activate 'MQTT ACL Endpoint status' (this is necessary only if you have opted for the secure _esthesis_ MQTT server).
* Go to Settings > Provisioning and enter the URL of your provisioning endpoint. Do not forget
to also use the port under which your provisioning endpoint resides.

* Register the MQTT server under Infrastructure > MQTT with the following details: +
    Name: `mqtt-server` +
    IP: `ssl://localhost:8883` (or `tcp://localhost:1883` if you are using a non-secure MQTT server) +
    State: `Active` +
    Tags: Use the tag you created above +
    CA certificate: The Certificate Authority you created (not necessary for non-secure MQTT server) +
    Client certificate: The certificate for the platform (not necessary for non-secure MQTT server) +
    Client private key: The private key for the platform (not necessary for non-secure MQTT server)

You now have an _esthesis_ platform server ready to accept device registration and data.

=== Running the runtime client (registering a simulated device)

To startup a simulated client device follow the instructions on link:../developer_guide/developer_guide.adoc#simulating-multiple-clients[Simulating multiple clients].

=== Configure data ingestion

To allow _esthesis_ platform to receive data from devices you need to setup a data storage
mechanism; in _esthesis+ terminology, this is a data sink.

.Configure a data sink
* Make sure you have an InfluxDB running (with a database and user credentials you can use).
* Go to Settings > Data sinks and choose 'Create'.
* Register a data sink with the following details: +
   Enabled: `true` +
   Name: `influxdb` +
   Driver: `InfluxDB` +
   Metadata/Telemetry handler: Choose all four +
   Configuration: +
    ```username: esthesis   +
    password: esthesis +
    databaseName: esthesis +
    databaseUrl: http://minikube:32108 +
    retentionPolicy: default +
    queueSize: 1000```
