= Administrator guide
Doc Writer <esthesis@eurodyn.com>
:toc:
:imagesdir: assets/images
:homepage: https://esthesis.com
:icons: font
:sectanchors:
:sectlinks:
:sectnums:

This is the _Administrator guide_ for _esthesis_ platform. It shows you in detail all the different options and configuration knobs of _esthesis_ while providing you valuable hints & tips on how you can use _esthesis_ in production.

== Quick configuration
How many times have you installed a new product, finding yourself having to read a ton of documentation on how to set it up before you can even start testing it? Well, _esthesis_ might also have a ton of documentation, however that does not prevent us from showing you how you can quickly set it up to have a test working platform in under 10'. Ready?

TIP: Make sure you have a complete installation done first following your preferred method from the link:installation_guide.adoc[Installation guide].

WARNING: The quick setup instructions depicted here are not suggested for anything else than a test lab. If you consider using _esthesis_ in anything wider than your local network make sure you follow (TBC) first.

=== Platform server configuration

* Login to _esthesis_ management ui.
* Create a Certificate Authority, name it `root-ca`.
** Select `root-ca` and download its certificate in Base64 format (`root-ca.crt.base64`).
* Create a Certificate, name it `platform`, signed by `root-ca`.
** Select `platform` and download its certificate and private key in Base64 format (`platform.crt.base64`, `platform.key.base64`).
* Create a tag to identify your devices with, name it `default`.
* Go to Settings > Security and choose `platform` as Platform certificate.
* Go to Settings > Device registration and choose `platform` as Root Certificate Authority.
* Go to Settings > Device registration and choose 'Open registration' (or any other mode you need).
* Go to Settings > Networking and activate 'MQTT ACL Endpoint status'.
* Go to Settings > Provisioning and enter the URL of your provisioning endpoint. This can be the URL
of your platform instance or the URL of the provisioning proxy if you have deployed one. Do not forget
to also use the port under which your provisioning endpoint resides.

* Boot up a secure MQTT server, so your devices have a target to submit data to: +

With Docker:

    docker run --rm -p 8883:8883  \
    -e CA_CERT="$(< root-ca.crt.base64)" \
    -e MOSQUITTO_CERT="$(< platform.crt.base64)" \
    -e MOSQUITTO_KEY="$(< platform.key.base64)" \
    -e ESTHESIS_PLATFORM_IP=platform-ip \
    -e ESTHESIS_PLATFORM_HOST_HEADER=localhost \
    -e ESTHESIS_PLATFORM_PORT=platform-port \
    -e ACL_CACHE_TIME=300 \
    -e ACL_CACHE_JITTER=60 \
    -e ACL_LOG=true \
    esthesis/esthesis-docker-mosquitto

With Kubernetes, using the `esthesis-is-mqtt-cert-deployment`:

    (TBC)

Using the

TIP: Change platform-ip and platform-port to your own values.

* Register the MQTT server under Infrastructure > MQTT with the following details: +
    Name: `mqtt1` +
    IP: `ssl://localhost:8883` +
    State: `Active` +
    Tags: `Default` +
    CA certificate: `root-ca` +
    Client certificate: `platform` +
    Client private key: `platform`

You now have an _esthesis_ platform server ready to accept device registration and data.

=== Running the runtime client (registering a simulated device)

To startup a simulated client device follow the instructions on link:../developer_guide/developer_guide.adoc#simulating-multiple-clients[Simulating multiple clients].

=== Configure data ingestion

To allow _esthesis_ platform to receive data from devices you need to setup a data storage
mechanism; in _esthesis+ terminology, this is a data sink.

.Configure a data sink
* Make sure you have an InfluxDB running (with a database and user credentials you can use).
* Go to Settings > Data sinks and choose 'Create'.
* Register a data sink with the following details: +
   Enabled: `true` +
   Name: `influxdb` +
   Driver: `InfluxDB` +
   Metadata/Telemetry handler: Choose all four +
   Configuration: +
    ```username: esthesis   +
    password: esthesis +
    databaseName: esthesis +
    databaseUrl: http://minikube:32108 +
    retentionPolicy: default +
    queueSize: 1000```
