---
##################################################################################################
# Environments definitions
##################################################################################################
environments:
  default:
    values:
      - devMode: false
      - devHost: ""
      - helmfileDevMode: {{ env "HELMFILE_DEV_MODE" | default false }}
  dev:
    values:
      - devMode: true
      - devHost: {{ env "DEV_HOST" }}
      - helmfileDevMode: {{ env "HELMFILE_DEV_MODE" | default true }}
      - kafkaBootstrapServers: {{ env "KAFKA_BOOTSTRAP_SERVERS" | default "kafka.esthesis.localdev:9094" }}
      - camundaGatewayUrlCluster: {{ env "CAMUNDA_GATEWAY_URL_CLUSTER" | default "camunda-zeebe-gateway.esthesis.localdev:26500" }}

---
##################################################################################################
# Default values
##################################################################################################
helmDefaults:
  timeout: 1800

---
##################################################################################################
# Default state values
##################################################################################################
values:
  - esthesisVersion: "3.0.0-SNAPSHOT"
  - timezone: {{ env "TIMEZONE" | default "Europe/Athens" }}
  - esthesisLogLevel: {{ env "ESTHESIS_LOG_LEVEL" | default "WARN" }}
  - esthesisAdminUsername: {{ env "ESTHESIS_ADMIN_USERNAME" | default "esthesis-admin" }}
  - esthesisAdminPassword: {{ env "ESTHESIS_ADMIN_PASSWORD" | default "esthesis-admin" }}
  - esthesisSystemUsername: {{ env "ESTHESIS_SYSTEM_USERNAME" | default "esthesis-system" }}
  - esthesisSystemPassword: {{ env "ESTHESIS_SYSTEM_PASSWORD" | default "esthesis-system" }}
  # MongoDB
  - mongoDbEnabled: {{ env "MONGODB_ENABLED" | default true }}
  - mongoDbUrlCluster: {{ env "MONGODB_URL_CLUSTER" | default "mongodb://mongodb:27017" }}
  - mongoDbDatabase: {{ env "MONGODB_DATABASE" | default "esthesiscore" }}
  - mongoDbUsername: {{ env "MONGODB_USERNAME" | default .StateValues.esthesisSystemUsername }}
  - mongoDbPassword: {{ env "MONGODB_PASSWORD" | default .StateValues.esthesisSystemPassword }}
  - mongoDbReplicaSets: {{ env "MONGODB_REPLICA_SETS" | default 1 }}
  - mongoDbArbiters: {{ env "MONGODB_ARBITERS" | default 0 }}
  # esthesis UI
  - esthesisUiIngressHostname: {{ env "ESTHESIS_UI_INGRESS_HOSTNAME" | default "esthesis-core.esthesis.localdev" }}
  - esthesisUiLogoutUrl: {{ env "ESTHESIS_UI_LOGOUT_URL" | default "/logout" }}
  # OIDC
  - oidcAuthorityUrlExternal: {{ env "OIDC_AUTHORITY_URL_EXTERNAL" | default "https://keycloak.esthesis.localdev/realms/esthesis" }}
  - oidcAuthorityUrlCluster: {{ env "OIDC_AUTHORITY_URL_CLUSTER" | default "http://keycloak/realms/esthesis" }}
  - oidcDiscoveryUrlCluster: {{ env "OIDC_DISCOVERY_URL_CLUSTER" | default "http://keycloak/realms/esthesis/.well-known/openid-configuration" }}
  - oidcJwtVerifyLocationCluster: {{ env "OIDC_JWT_VERIFY_LOCATION_CLUSTER" | default "http://keycloak/realms/esthesis/protocol/openid-connect/certs" }}
  - kafkaBootstrapServers: {{ env "KAFKA_BOOTSTRAP_SERVERS" | default "kafka:9092" }}
  # Camunda
  - camundaGatewayUrlCluster: {{ env "CAMUNDA_GATEWAY_URL_CLUSTER" | default "camunda-zeebe-gateway:26500" }}
  # Redis
  - redisHosts: {{ env "REDIS_HOSTS" | default "redis.esthesis.localdev:6379"}}
  # RabbitMQ
  - rabbitmqErlangCookie: {{ env "RABBITMQ_ERLANG_COOKIE" | default .StateValues.esthesisSystemUsername }}

---
##################################################################################################
# Release definitions
##################################################################################################
releases:
  - name: esthesis-core
    chart: {{ .StateValues.helmfileDevMode | ternary "./" "esthesis/esthesis-core" | quote }}
    version: {{ .StateValues.esthesisVersion | quote }}
    values:
      - devMode: {{ .StateValues.devMode }}
      - devHost: {{ .StateValues.devHost | quote }}
      - quarkus:
          log:
            min-level: "TRACE"
            level: {{ .StateValues.esthesisLogLevel | quote }}
            category:
              esthesis:
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.jboss.resteasy.reactive":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.mongodb.panache.common.runtime":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "org.mongodb":
                level: {{ .StateValues.esthesisLogLevel | quote }}
              "io.quarkus.oidc.token.propagation.reactive":
                level: {{ .StateValues.esthesisLogLevel | quote }}
      - esthesisAdminUsername: {{ .StateValues.esthesisAdminUsername | quote }}
      - esthesisAdminPassword: {{ .StateValues.esthesisAdminPassword | quote }}
      - esthesisSystemUsername: {{ .StateValues.esthesisSystemUsername | quote }}
      - esthesisSystemPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      - esthesisUiIngressHostname: {{ .StateValues.esthesisUiIngressHostname | quote }}
      - esthesisUiLogoutUrl: {{ .StateValues.esthesisUiLogoutUrl | quote }}
      - kafkaBootstrapServers: {{ .StateValues.kafkaBootstrapServers | quote }}
      # OIDC
      - oidcAuthorityUrlExternal: {{ .StateValues.oidcAuthorityUrlExternal | quote }}
      - oidcAuthorityUrlCluster: {{ .StateValues.oidcAuthorityUrlCluster | quote }}
      - oidcDiscoveryUrlCluster: {{ .StateValues.oidcDiscoveryUrlCluster | quote }}
      - oidcJwtVerifyLocationCluster: {{ .StateValues.oidcJwtVerifyLocationCluster | quote }}
      # MongoDB
      - mongoDbEnabled: {{ .StateValues.mongoDbEnabled }}
      - mongoDbUrlCluster: {{ .StateValues.mongoDbUrlCluster | quote }}
      - mongoDbDatabase: {{ .StateValues.mongoDbDatabase | quote }}
      - mongoDbUsername: {{ .StateValues.esthesisSystemUsername | quote }}
      - mongoDbPassword: {{ .StateValues.esthesisSystemPassword | quote }}
      - mongoDbReplicaSets: {{ .StateValues.mongoDbReplicaSets }}
      - mongoDbArbiters: {{ .StateValues.mongoDbArbiters }}
      # REDIS
      - redisHosts: {{ .StateValues.redisHosts | quote }}
      # RabbitMQ
      - rabbitmqErlangCookie: {{ .StateValues.rabbitmqErlangCookie |quote }}
      # Camunda
      - camundaGatewayUrlCluster: {{ .StateValues.camundaGatewayUrlCluster | quote }}
