apiVersion: v1
entries:
  esthesis-device:
  - apiVersion: v2
    appVersion: 2.0.1-SNAPSHOT
    created: "2022-02-22T16:44:40.744464+02:00"
    description: A Helm chart to deploy an esthesis device client.
    digest: 5c58ea270466d89866937c6a5aedce75393d4f321457155657f2507cd4e03a6d
    home: https://esthes.is
    icon: https://esthes.is/media/logo.png
    maintainers:
    - email: esthesis@eurodyn.com
      name: European Dynamics SA
      url: https://www.eurodyn.com
    name: esthesis-device
    sources:
    - https://github.com/esthesisiot
    type: application
    urls:
    - esthesis-device-1.0.0.tgz
    version: 1.0.0
  esthesis-platform:
  - apiVersion: v2
    appVersion: 2.0.1-SNAPSHOT
    created: "2022-02-22T16:44:40.744985+02:00"
    description: A Helm chart to deploy eshtesis IoT platform.
    digest: 3d16a9f05b6228999ae214461e1ba19abcfdde75c74f0620d80f82e747e2a51d
    home: https://esthes.is
    icon: https://esthes.is/media/logo.png
    maintainers:
    - email: esthesis@eurodyn.com
      name: European Dynamics SA
      url: https://www.eurodyn.com
    name: esthesis-platform
    sources:
    - https://github.com/esthesisiot
    type: application
    urls:
    - esthesis-platform-1.0.0.tgz
    version: 1.0.0
generated: "2022-02-22T16:44:40.743956+02:00"
