= Developer guide
Doc Writer <esthesis@eurodyn.com>
:toc:
:imagesdir: assets/images
:homepage: https://esthesis.com
:icons: font
:sectanchors:
:sectlinks:
:sectnums:

[TBC] Link to dev setup: Minikube for development

[TBC] Talk about Skaffold:
_esthesis_ Kubernetes configuration also support https://skaffold.dev/[Skaffold] to merge...

== Setting up a development environment
To setup your local environment for develepoment, refer to the Installation Guide document, section
4.3, Minikube for developers.

== Platform UI

== Platform server

== Runtime client

=== Simulating multiple clients
You can perform a simple stress test by simulating multiple clients connecting to your _esthesis_ platform
using the following "one-liner" in your Linux shell:
```
for i in {1..1}; do\
    hardwareId=device$i \
    storageRoot="$(echo ~$USER)/.esthesis/devices/device$i" \
    registrationUrl="http://localhost:46000" \
    incomingSigned=false \
    incomingEncrypted=false \
    provisioningSigned=false \
    provisioningEncrypted=false \
    outgoingSigned=false \
    outgoingEncrypted=false \
    tags=demo \
    proxyMqtt=true \
    proxyMqttPort=$((4000 + $i)) \
    proxyWeb=true \
    proxyWebPort=$((14000 + $i)) \
    java -jar target/esthesis-device-java-1.0.0-SNAPSHOT.jar & \
done
```

TIP: Do not forget to replace \http://localhost:46000 with the actual URL of your _esthesis_ platform
registration URL as well as choosing tags you have already defined.

TIP: To quickly kill all simulated processes you can execute: +
`kill -9 $(ps -fA |grep -i "java -jar target/esthesis-device" | awk '{print $2}')`

To work with code under development, you can replace the last line with:
```
mvn spring-boot:run -Dspring-boot.run & \
```

== Utilities
=== Capturing database schema changes
You can edit the schema of the _esthesis_ platform database and automatically capture your changes
into Liquibase scripts by executing:
```
#!/usr/bin/env bash
# The location of esthesis source code.
ESTHESIS_SRC_ROOT=/esthesis-iot
# The location of QLACK source code.
QLACK_SRC_ROOT=/qlack
# How the address of your Docker host is resolved.
DOCKER_HOST=docker.for.mac.host.internal

KUBECTL_DB_POD=$(kubectl get pods | grep ps-db | awk -F ' ' '{print $1}')
echo "DB POD: $KUBECTL_DB_POD"
kubectl port-forward $KUBECTL_DB_POD 45000:3306 &

echo "Waiting for port forward..."
while ! nc -z localhost 45000; do
  sleep 1
done
echo "Port forward active."

docker run --rm \
-e DRIVER=com.mysql.cj.jdbc.Driver \
-e DB_HOST=$DOCKER_HOST \
-e DB_PORT=45000 \
-e DB_SCHEMA=esthesis \
-e DB=mysql \
-e DB_USER=root \
-e DB_PASS=root \
-e CHANGELOG=/db/changelog/db.changelog-master.yaml \
-e DIFFLOG=/db/changelog/changes \
-e AUTHOR=European\ Dynamics \
-v $ESTHESIS_SRC_ROOT/esthesis-platform/esthesis-platform-server/src/main/resources/db:/db \
-v $QLACK_SRC_ROOT/QLACK-Fuse/qlack-fuse-settings/src/main/resources/db/changelog/qlack-fuse-settings:/db/changelog/qlack-fuse-settings:ro \
-v $QLACK_SRC_ROOT/QLACK-Fuse/qlack-fuse-aaa/src/main/resources/db/changelog/qlack-fuse-aaa:/db/changelog/qlack-fuse-aaa:ro \
-v $QLACK_SRC_ROOT/QLACK-Fuse/qlack-fuse-audit/src/main/resources/db/changelog/qlack-fuse-audit:/db/changelog/qlack-fuse-audit:ro \
eurodyn/qlack-tools-liquibase \
diffChangeLog.sh

rm -rf $ESTHESIS_SRC_ROOT/esthesis-platform/esthesis-platform-server/src/main/resources/db/changelog/qlack-fuse-*

KUBECTL_PROCESS=$(ps -fa |grep -i kubectl |grep 45000:3306 | awk -F ' ' '{print $2}')
kill -9 $KUBECTL_PROCESS
```

=== Accessing InfluxDB via Chronograf
Your InfluxDB is running in a container inside your Minikube environment. To access it, you will
boot a Chronograf container in your PC, so you need to ensure that it can see your InfluxDB.

First, setup a port forward from an arbitrary port of your PC to InfluxDB's port
(make sure you change the name of the deployment as it exists in your local setup):

    kubectl port-forward $(kubectl get pods | grep esthesis-ds-influxdb-deployment | awk -F ' ' '{print $1}') 5000:8086

Next, startup the Chronograf Docker container:

    docker run --rm --name telegraf -p 8888:8888 chronograf --influxdb-url=http://docker.for.mac.host.internal:5000

You should pay attention to the `influxdb-url` parameter. The above, works for Mac; similarly, you can use it in
Windows via `docker.for.win.host.internal`, however in Linux you need to startup your container with `--net=host` and use
`localhost` instead.
