= Installation guide
Doc Writer <esthesis@eurodyn.com>
:toc:
:imagesdir: assets/images
:homepage: https://esthesis.com
:icons: font
:sectanchors:
:sectlinks:

_esthesis_ comprises of many different modules, some of them optional and some of them mandatory. You can install a barebones edition with only the main platform itself, using infrastructure you already have in place - such as a MySQL database, an InfluDB cluster, etc. You can also use one of _esthesis_ configurations to create Docker and/or Kubernetes environments including optional components or not. Finally, if containers are not your thing, you can go low-level and directly run the executable JAR files of _esthesis_.

TIP: We suggest you are a tid bit familiar with _esthesis_ link:architecture.adoc[Architecture] before you choose which installation option is suitable for your use case.

== Binaries installation
(TBC)

== Docker installation
(TBC)

== AWS installation
(TBC)

== Azure installation
(TBC)

== Google Cloud platform installation
(TBC)

== Virtualised installation
The virtualised installation provides you with a ready-made Virtual Machine containing everything you need to run the _esthesis_ platform. Because everything is installed into a single VM, such installations are not meant to be used in production setups, however it may be the quickest way from nothing to a running platform in case you want to quickly see how _esthesis_ works.

(TBC)

=== VMWare
(TBC)

=== VirtualBox
(TBC)

== Kubernetes installation
    Location: esthesis-setup/k8s

_esthesis_ provides multiple YAML files to allow you to install it on a Kubernetes cluster, practically, running a single command on your CLI. _esthesis_ allows you to choose which parts of its own resources configuration will be created for your and which parts of your existing infrastructure will be used in your installation.

.Configuration management
All Kubernetes resource configurations are complemented with https://kustomize.io/[Kustomize], so that you can easily customize them to your environment without having the touch the original YAML files.

There are, currently, three different types of installations targeting Kubernetes as presented next.

=== All-in-one
    Location: esthesis-setup/k8s/_setups/all
    Suitable for production use: Yes

The all-in-one installation includes all mandatory and most of the optional components of _esthesis_, assuming you have no local infrastructure you intend to reuse. It is the quickest way to have a complete platform up and running with all necessary supporting resources automatically being created for you.

.What is included
* (TBC)

.How to run it
Drop to your CLI and switch to esthesis-setup/k8s/_setups/all.

=== All-in-one for Minikube
    Location: esthesis-setup/k8s/_setups/all-minikube
    Suitable for production use: No

The All-in-one for Minikube is an instalation type similar to the  link:#all-in-one[All-in-one] with the main difference being that is targeting a local Minikube environment. It includes all mandatory and optional components, providing a complete platform with the full set of functionality readily available. All user-accessible containers in this installation type are exposing their ports using a Kubernetes `NodePort`, so they are easily accessible using `localhost`. This is the quickest way to have a full demo of _esthesis_ in your local machine without having to configure or install any additional components. Apparently, because of Minikube, this is not an installation type suitable for a production environment.

.What is included
The following resources are created:

|===
|Component |Host |Port |Type

|MySQL
|N/A
|N/A
|Platform service

|MySQL admin UI
|minikube IP
|32002
|Platform service

|MySQL backup
|N/A
|N/A
|Platform service

|InfluxDB
|N/A
|N/A
|Data sink

|InfluxDB admin UI
|minikube IP
|32003
|Data sink

|InfluxDB backup
|N/A
|N/A
|Data sink

|MySQL
|N/A
|N/A
|Data sink

|MySQL admin UI
|minikube IP
|32007
|Data sink

|MySQL backup
|N/A
|N/A
|Data sink

|Mosquitto
|minikube IP
|32004
|Ingestion service

|Provisioning proxy
|minikube IP
|32005
|Platform proxy

|Registration proxy
|minikube IP
|32006
|Platform proxy

|esthesis platform server
|N/A
|N/A
|esthesis platform

|esthesis platform admin UI
|minikube IP
|32000
|esthesis platform
|===

TIP: You can create an entry in your `hosts` file with the IP address of your Minikube to conveniently access the above URLs, for example, \http://minikube:32000.

.How to install

* Drop to your CLI and switch to `esthesis-setup/k8s/_setups/all-minikube`.
* Setup access to the docker registry from which _esthesis_ images are to be pulled: `kubectl create secret docker-registry esthesis-dockerhub --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>`
* Execute `kustomize build . | kubectl apply -f -`

TIP: Create a namespace, so that you can easily delete all resources when no longer needed.

.Post-installation
* Setup the link:#esthesis-is-mqtt-cert-deployment[secure MQTT server].

=== Minikube for developers
    Location: esthesis-setup/k8s/_setups/all-minikube-dev
    Suitable for production use: No

The Minikube for developers installation type is suitable to quickly setup a development environment in your local machine. It is similar to the link:#all-in-one-for-minikube[All-in-one for Minikube], however it does not include two of the main mandatory artifacts: The _esthesis_ platform server and the _esthesis_ platform UI. These are left out, so that you can run them in your preferred development environment.

Note that this setup type exposes services at different ports than the All-in-one for Minikube, so that you can have a development environment as well as a test environment running in parallel in your local machine.

.What is included
The following resources are created:

|===
|Component |Host |Port |Type

|MySQL
|minikube IP
|32101
|Platform service

|MySQL admin UI
|minikube IP
|32102
|Platform service

|MySQL backup
|N/A
|N/A
|Platform service

|InfluxDB
|N/A
|N/A
|Data sink

|InfluxDB admin UI
|minikube IP
|32103
|Data sink

|InfluxDB backup
|N/A
|N/A
|Data sink

|MySQL
|N/A
|N/A
|Data sink

|MySQL admin UI
|minikube IP
|32107
|Data sink

|MySQL backup
|N/A
|N/A
|Data sink

|Mosquitto
|minikube IP
|32104
|Ingestion service

|===

TIP: You can create an entry in your `hosts` file with the IP address of your Minikube to conveniently access the above URLs, for example, \http://minikube:32103.

.How to install

* Drop to your CLI and switch to `esthesis-setup/k8s/_setups/all-minikube-dev`.
* Setup access to the docker registry from which _esthesis_ images are to be pulled: `kubectl create secret docker-registry esthesis-dockerhub --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>`
* Execute `kustomize build . | kubectl apply -f -`

TIP: Create a namespace, so that you can easily delete all resources when no longer needed.

.Post-installation
* Setup the link:#esthesis-is-mqtt-cert-deployment[secure MQTT server].
* _esthesis_ platform server is already specified with a JDBC URL pointing to the database running in Minikube (minikube:), so no reconfiguration is necessary.


== General configuration
=== Default credentials
Username: `admin@esthes.is` +
Password: `admin`

=== esthesis-is-mqtt-cert-deployment
Some of the setup types include an MQTT server (based on Eclipse Mosquitto) that is configured to authenticate clients by using certificates. This is to only allow devices for which you have handed a certificate to be able to send  messages to the _esthesis_ platform. However, when you first perform an installation of _esthesis_ the details of such certificates are not yet known (i.e. you need to create a  as well as a link:TBC[Platform certificate], so the deployment fails reporting that `esthesis-is-mqtt-cert-secret` is missing. Until this secret is created the deployment cannot proceed. Here is how you prepare this secret:

* Create a link:TBC[Certificate Authority] in _esthesis_ platform. Let us call it "root-ca".
* Create a link:TBC[Certificate] in _esthesis_ platform using the above Certificate Authority to sign it.
* Export the Certificate Authority (TBC)

